# Generated by Django 4.2.5 on 2023-09-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='catagory',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
